export default {
  alpha2Code: { type: String, required: true },
  alpha3Code: { type: String, required: true },
  numericCode: { type: Number, required: true },
  officialName: { type: String, required: true },
  officialNameLocal: { type: String, required: true },
  fullName: { type: String },
  fullNameLocal: { type: String },
  capital: { type: String },
  capitalLocal: { type: String },
  continent: { type: String, required: true, default: '-' },
  language: [
    { type: String, required: true },
  ],
  localISOCode: { type: String },
  latitude: { type: Number, required: true },
  longitude: { type: Number, required: true },
  currency: { type: String },
  currencyCode: { type: String },
  timeZone: { type: String },
  internetTLD: { type: String },
  phoneCode: { type: String },
  daylightSavingFlag: { type: String, required: true },
  specialFlag: { type: String, required: true },
  flagImageUrl: { type: String },
  memo: [
    {
      id: { type: String, required: true },
      content: { type: String, required: true },
    },
  ],
}
